Add `/question solve` command for forums
pngwn/svelte-bot pull request #40
Opened 2022-09-28 03:16 UTC by gtm-nayan

2022-09-28 15:03 UTC, ghostdevv commented on src/commands/questions/question.ts
> +import { i_solemnly_swear_it_is_a_forum_thread } from '../../utils/smh_typescript.js';
10/10

2022-09-28 15:04 UTC, ghostdevv requested changes

2022-09-28 15:04 UTC, ghostdevv commented on src/commands/questions/question.ts
> +		/* @__PURE__ */ i_solemnly_swear_it_is_a_forum_thread(thread);
why do you need the pure marking

2022-09-29 02:33 UTC, gtm-nayan commented on src/commands/questions/question.ts
> +		/* @__PURE__ */ i_solemnly_swear_it_is_a_forum_thread(thread);
Don't really *need* it but, since by that point it's known that the thread is a forum (because the only help channel is), I wanted esbuild to just remove that function call altogether.

2022-09-29 18:43 UTC, ghostdevv commented on src/commands/questions/question.ts
> +		/* @__PURE__ */ i_solemnly_swear_it_is_a_forum_thread(thread);
Oki

2022-09-29 18:43 UTC, ghostdevv approved these changes

2022-09-30 01:03 UTC, merged